version: "{build}"
install:
  - ps: [Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
  - gem install dev --quiet --no-ri --no-rdoc
build: off
test_script:
  - rake
environment:
  matrix:
    - ruby_version: "200-x64"

