using System;
using System.Collections.Generic;
using LiteDB;

namespace Node.Net.Service.Logging;

/// <summary>
/// Represents a single log entry compatible with Serilog structured logging format and Microsoft.Extensions.Logging.
/// </summary>
/// <remarks>
/// This class is designed to be compatible with both Serilog structured logging and Microsoft.Extensions.Logging.
/// It includes all essential log information including timestamp, level, message, structured properties, exception details, and source context.
/// </remarks>
public class LogEntry
{
    /// <summary>
    /// Gets or sets the unique identifier for the log entry (primary key, auto-generated by LiteDB).
    /// </summary>
    public ObjectId Id { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when the log entry was created.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; }

    /// <summary>
    /// Gets or sets the log level (Debug, Info, Warn, Error, Fatal).
    /// </summary>
    public string Level { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the rendered log message.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the message template (if available from structured logging).
    /// </summary>
    public string? MessageTemplate { get; set; }

    /// <summary>
    /// Gets or sets the structured data properties (key-value pairs).
    /// </summary>
    public Dictionary<string, object>? Properties { get; set; }

    /// <summary>
    /// Gets or sets the serialized exception details (if exception was logged).
    /// </summary>
    public string? Exception { get; set; }

    /// <summary>
    /// Gets or sets the source context (typically type/namespace name).
    /// </summary>
    public string? SourceContext { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this entry was manually created (true) or automatically captured (false).
    /// </summary>
    /// <remarks>
    /// Automatically captured entries (IsManualEntry = false) are read-only and cannot be updated.
    /// Only manually created entries (IsManualEntry = true) can be edited.
    /// </remarks>
    public bool IsManualEntry { get; set; }

    /// <summary>
    /// Validates the log entry according to validation rules.
    /// </summary>
    /// <exception cref="ArgumentException">Thrown when validation fails.</exception>
    public void Validate()
    {
        if (Timestamp > DateTimeOffset.UtcNow.AddMinutes(1)) // Allow 1 minute clock skew
        {
            throw new ArgumentException("Timestamp must not be in the future.", nameof(Timestamp));
        }

        if (string.IsNullOrWhiteSpace(Level))
        {
            throw new ArgumentException("Level must not be null or empty.", nameof(Level));
        }

        var validLevels = new[] { "Debug", "Info", "Warn", "Error", "Fatal" };
        if (Array.FindIndex(validLevels, level => string.Equals(level, Level, StringComparison.OrdinalIgnoreCase)) < 0)
        {
            throw new ArgumentException($"Level must be one of: {string.Join(", ", validLevels)}", nameof(Level));
        }

        if (string.IsNullOrWhiteSpace(Message))
        {
            throw new ArgumentException("Message must not be null or empty.", nameof(Message));
        }
    }
}
